apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: chronograf
  name: chronograf
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chronograf
    spec:
      containers:
      - env:
        - name: CHRONOGRAF_BIND
          value: 0.0.0.0:10000
        image: chronograf:0.13
        name: chronograf
        ports:
        - containerPort: 10000
        resources: {}
      restartPolicy: Always
status: {}
