apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: nats
  name: nats
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nats
    spec:
      containers:
      - image: nats:0.8.0
        name: nats
        ports:
        - containerPort: 4222
        - containerPort: 8222
        resources: {}
      restartPolicy: Always
status: {}
