apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: positionpublisher
  name: positionpublisher
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: positionpublisher
    spec:
      containers:
      - args:
        - --broker
        - nats
        - --registry
        - nats
        - --transport
        - nats
        - --broker_address
        - nats:4222
        - --registry_address
        - nats:4222
        - --transport_address
        - nats:4222
        image: positionpublisher
        name: positionpublisher
        resources: {}
      restartPolicy: Always
status: {}
