FROM sumoproto:0.1

LABEL maintainer="min<min_ju@invastsec.jp>"

WORKDIR /go/src/github.com/ilovelili/sumoproto/services/marketdata/initiator

COPY . /go/src/github.com/ilovelili/sumoproto

# develop a new package from scratch
RUN go install

ENTRYPOINT ["initiator"]