FROM sumoproto:0.1

LABEL maintainer="min<min_ju@invastsec.jp>"

WORKDIR /go/src/github.com/ilovelili/sumoproto/services/position/publisher

COPY . /go/src/github.com/ilovelili/sumoproto

RUN go install

ENTRYPOINT ["publisher"]