FROM sumoproto:0.1

LABEL maintainer="minju<route666@live.cn>"

WORKDIR /go/src/github.com/ilovelili/sumoproto/services/ticksubscriber

COPY . /go/src/github.com/ilovelili/sumoproto

# develop a new package from scratch
RUN go install

ENTRYPOINT ["ticksubscriber"]