// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ilovelili/sumoproto/services/tickrecorder/proto/tick.proto

/*
Package go_srv_TickRecorder is a generated protocol buffer package.

It is generated from these files:
	github.com/ilovelili/sumoproto/services/tickrecorder/proto/tick.proto

It has these top-level messages:
	Tick
	Trade
*/
package go_srv_TickRecorder

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Tick struct {
	Time   int64   `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Bid    float64 `protobuf:"fixed64,2,opt,name=bid" json:"bid,omitempty"`
	Ask    float64 `protobuf:"fixed64,3,opt,name=ask" json:"ask,omitempty"`
	Last   float64 `protobuf:"fixed64,4,opt,name=last" json:"last,omitempty"`
	Pair   string  `protobuf:"bytes,5,opt,name=pair" json:"pair,omitempty"`
	Broker string  `protobuf:"bytes,6,opt,name=broker" json:"broker,omitempty"`
}

func (m *Tick) Reset()                    { *m = Tick{} }
func (m *Tick) String() string            { return proto.CompactTextString(m) }
func (*Tick) ProtoMessage()               {}
func (*Tick) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Tick) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Tick) GetBid() float64 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *Tick) GetAsk() float64 {
	if m != nil {
		return m.Ask
	}
	return 0
}

func (m *Tick) GetLast() float64 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *Tick) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Tick) GetBroker() string {
	if m != nil {
		return m.Broker
	}
	return ""
}

type Trade struct {
	Time   int64   `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Price  float64 `protobuf:"fixed64,2,opt,name=price" json:"price,omitempty"`
	Amount float64 `protobuf:"fixed64,3,opt,name=amount" json:"amount,omitempty"`
	Type   int32   `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	Broker string  `protobuf:"bytes,6,opt,name=broker" json:"broker,omitempty"`
	Pair   string  `protobuf:"bytes,7,opt,name=pair" json:"pair,omitempty"`
}

func (m *Trade) Reset()                    { *m = Trade{} }
func (m *Trade) String() string            { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()               {}
func (*Trade) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Trade) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Trade) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Trade) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Trade) GetBroker() string {
	if m != nil {
		return m.Broker
	}
	return ""
}

func (m *Trade) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func init() {
	proto.RegisterType((*Tick)(nil), "go.srv.TickRecorder.Tick")
	proto.RegisterType((*Trade)(nil), "go.srv.TickRecorder.Trade")
}

func init() {
	proto.RegisterFile("github.com/ilovelili/sumoproto/services/tickrecorder/proto/tick.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbd, 0x6a, 0xec, 0x30,
	0x10, 0x85, 0xd1, 0xf5, 0xcf, 0x25, 0xaa, 0x12, 0x6f, 0x08, 0x2a, 0xcd, 0x56, 0xae, 0xe4, 0x22,
	0x6f, 0xb0, 0xb0, 0x65, 0x20, 0x98, 0x7d, 0x01, 0x59, 0x1e, 0x1c, 0x21, 0xd9, 0x63, 0x46, 0xb2,
	0x21, 0x4d, 0xfa, 0xbc, 0x75, 0x90, 0x6c, 0x92, 0x26, 0xe9, 0xce, 0xf9, 0x24, 0x8d, 0x3e, 0x86,
	0x5f, 0x47, 0x13, 0xde, 0xd6, 0x5e, 0x6a, 0x9c, 0x5a, 0xe3, 0x70, 0x03, 0x67, 0x9c, 0x69, 0xfd,
	0x3a, 0xe1, 0x42, 0x18, 0xb0, 0xf5, 0x40, 0x9b, 0xd1, 0xe0, 0xdb, 0x60, 0xb4, 0x25, 0xd0, 0x48,
	0x03, 0x50, 0xbb, 0x9f, 0x45, 0x24, 0x53, 0xac, 0x4e, 0x23, 0x4a, 0x4f, 0x9b, 0xbc, 0x19, 0x6d,
	0xbb, 0xe3, 0xd6, 0xf9, 0x83, 0xe7, 0xb1, 0x57, 0x15, 0xcf, 0x83, 0x99, 0x40, 0xb0, 0x9a, 0x35,
	0x59, 0x97, 0x72, 0x75, 0xcf, 0xb3, 0xde, 0x0c, 0xe2, 0x5f, 0xcd, 0x1a, 0xd6, 0xc5, 0x18, 0x89,
	0xf2, 0x56, 0x64, 0x3b, 0x51, 0x3e, 0xbd, 0x73, 0xca, 0x07, 0x91, 0x27, 0x94, 0x72, 0x64, 0x8b,
	0x32, 0x24, 0x8a, 0x9a, 0x35, 0x77, 0x5d, 0xca, 0xd5, 0x13, 0x2f, 0x7b, 0x42, 0x0b, 0x24, 0xca,
	0x44, 0x8f, 0x76, 0xfe, 0x64, 0xbc, 0xb8, 0x91, 0x1a, 0xe0, 0x57, 0x83, 0x47, 0x5e, 0x2c, 0x64,
	0x34, 0x1c, 0x0e, 0x7b, 0x89, 0xb3, 0xd4, 0x84, 0xeb, 0x1c, 0x0e, 0x91, 0xa3, 0xa5, 0x09, 0xef,
	0x0b, 0x24, 0x97, 0xa2, 0x4b, 0xf9, 0xaf, 0x7f, 0xbf, 0x1d, 0xff, 0xff, 0x38, 0x5e, 0x1a, 0x7e,
	0xd2, 0x38, 0x49, 0xef, 0x94, 0xb6, 0x12, 0x17, 0x98, 0x95, 0x1b, 0x31, 0x5c, 0x1e, 0x5e, 0x14,
	0x59, 0x08, 0xd7, 0x0d, 0xe6, 0xf0, 0x1a, 0x37, 0xe9, 0xfb, 0x32, 0x6d, 0xf4, 0xf9, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x6e, 0xe6, 0x95, 0x55, 0x9a, 0x01, 0x00, 0x00,
}
